import { ILocationApi } from '@modal/location-building-room.modal'
import { IUserCreationFormApi } from '@modal/user-creation.modal'

export const locationApiDefaultData: ILocationApi = {
  buildings: [
    {
      buildingAddress: '',
      buildingName: '',
      createAt: '',
      createdBy: '',
      deleted: false,
      id: 0,
      latitude: '',
      longitude: '',
      publish: true,
      rooms: [
        {
          createAt: '',
          createdBy: '',
          deleted: false,
          id: 0,
          publish: true,
          roomCapacity: 0,
          roomFloor: 0,
          roomName: '',
          roomType: '',
          updateAt: '',
          updatedBy: '',
        },
      ],
      updateAt: '',
      updatedBy: '',
      zipCode: '',
    },
  ],
  createAt: '',
  createdBy: '',
  deleted: false,
  id: 0,
  locationName: '',
  publish: true,
  updateAt: '',
  updatedBy: '',
}

export const userCreationApiDefaultData: IUserCreationFormApi = {
  address: '',
  buildingsDTO: [
    {
      buildingAddress: '',
      buildingName: '',
      createAt: '',
      createdBy: '',
      deleted: false,
      id: 0,
      latitude: '',
      locationsDTO: {
        createAt: '',
        createdBy: '',
        deleted: false,
        id: 0,
        locationName: '',
        publish: true,
        updateAt: '',
        updatedBy: '',
      },
      longitude: '',
      publish: true,
      updateAt: '',
      updatedBy: '',
      zipCode: '',
    },
  ],
  email: '',
  id: 0,
  name: '',
  password: '',
  phoneNumber: '',
  roomsDTO: {
    buildingsDTO: {
      buildingAddress: '',
      buildingName: '',
      createAt: '',
      createdBy: '',
      deleted: false,
      id: 0,
      latitude: '',
      locationsDTO: {
        createAt: '',
        createdBy: '',
        deleted: false,
        id: 0,
        locationName: '',
        publish: true,
        updateAt: '',
        updatedBy: '',
      },
      longitude: '',
      publish: true,
      updateAt: '',
      updatedBy: '',
      zipCode: '',
    },
    id: 0,
    roomCapacity: 0,
    roomFloor: 0,
    roomName: '',
    roomType: '',
  },
  userType: '',
  zipCode: '',
}
